---
- name: Install nginx
  apt: name=nginx state=present

#- name: Remove nginx default.conf
#  file: path=/etc/nginx/sites-enabled/default state=absent
#
#- name: Copy nginx site.conf
#  template: src=site.conf dest=/etc/nginx/sites-enabled/{{ site_name }}
#  notify: restart nginx